### ISSUE TITLE
Is it possible to obtain "session" using salesforcer?

### ISSUE THREAD

**Issue by Lulliter** [StevenMMortimer/salesforcer#10]
Hello, Is there a way to obtain "session" using salesforcer? (analog to **rforcecom::rforcecom.login**)

I ask because I would rather use **salesforcer::sf_auth()** to authenticate (withouth declaring my credentials in the code), but if I do I am not able to retrieve "session" - which, in turn, is an argument of the function  **rforcecom::rforcecom.getObjectDescription(session, objectName)** which is very useful for me. Thanks!

**Comment by StevenMMortimer** [comment]
Great question @Lulliter! If you authenticate using OAuth2.0 protocol (e.g. using `sf_auth()` without explicitly providing a username or password), then it will generate an OAuth token. This is different than authenticating with a username/password which is how RForcecom works. The salesforcer package supports session based authentication. If you'd like to authenticate using a username/password session and re-use it in `getObjectDescription()`, then you can do it like this:

```
library(salesforcer)

sf_auth(username = "test@gmail.com", 
        password = "{PASSWORD_HERE}",
        security_token = "{SECURITY_TOKEN_HERE}")

current_state <- salesforcer_state()
session <- c("sessionID" = current_state$session_id, 
             "instanceURL" = paste0(current_state$instance_url, "/"), 
             "apiVersion" = getOption("salesforcer.api_version"))

RForcecom::rforcecom.getObjectDescription(session, objectName)
```

**Comment by StevenMMortimer** [comment]
Before I close the issue, is there something specific about `getObjectDescription()` that you need to use it? Is it because it returns the picklist values as a `data.frame` with one row per field on the object?

You can use **salesforcer** to achieve the same output as `getObjectDescription()`  by running this code: 

```
# the salesforcer way
library(purrr)
obj_dat <- sf_describe_objects("Account", api_type="SOAP")[[1]]
acct_fields1 <- map_df(obj_dat[names(obj_dat) == "fields"], 
                       as.data.frame, 
                       stringsAsFactors=FALSE)

# the RForcecom way
acct_fields2 <- RForcecom::rforcecom.getObjectDescription(session, objectName='Account')
```

**Comment by StevenMMortimer** [comment]
@Lulliter I've replicated the `rforcecom.getObjectDescription()` function inside **salesforcer** so that you don't need to load **RForcecom** and use its old authentication method. I've also created a more aptly named function `sf_describe_object_fields()` which returns pretty much the same thing, but as a `tbl_df`. I'd recommend using it instead.

Since I just added this the functions are not on the CRAN version. You'll have to install from GitHub like this: 

```
devtools::install_github('StevenMMortimer/salesforcer')
```

Then play around with the changes like this: 

```
library(salesforcer)

# uncomment the authentication step if you don't have a cached .httr-oauth file
#sf_auth()

acct_fields <- sf_describe_object_fields('Account')
acct_fields %>% select(name, label, length, soapType, type)
```

**Comment by Lulliter** [comment]
Wow, this is great! Thanks so much! (also for the alternative options you provided)
