### ISSUE TITLE
Configuring SF Login using Okta

### ISSUE THREAD

**Issue by shambhu112** [StevenMMortimer/salesforcer#107]
my org has Okta based sfdc login. When I try the following 
sf_auth(login_url = "http://myorg.my.salesforce.com") I get the error

error=redirect_uri_mismatch&error_description=redirect_uri%20must%20match%20configuration

Note:  My org uses Okta and the normal sequence is that when I go to http://[myorg].my.salesforce.com  The site redirects me to an Okta screen.

**Comment by StevenMMortimer** [comment]
Hi @shambhu112 👋 Thanks for bringing up this scenario of logging in via Okta. I believe you have two options to resolve the issue:

1. Ask an administrator which login redirect uri's are accepted by your current configuration and then pass it to the package (e.g., `options(salesforcer.callback_url = "http://localhost:8888/my-app/signin.html/")`). I've included a screenshot below of the Okta configuration screen where this value is defined.

2. Update your Okta configuration to include salesforcer's default redirect uri (`http://localhost:1410/`) defined here: https://github.com/StevenMMortimer/salesforcer/blob/aef7aeeabcfc736e859eb18e9bfa56cf0cd2c178/R/zzz.R#L14 

If neither of these are possible or additional problems exist, then it might make sense to create your own "Connected App" within your Salesforce instance instead of using the one associated to the package because you will have more control over different configurations. Here is a link to get started: https://trailhead.salesforce.com/en/content/learn/modules/connected-app-basics/learn-about-connected-apps

----

**Screenshot of Okta configuration**
![image](https://user-images.githubusercontent.com/5299737/132013248-4fe7d9b8-5e4e-4530-9157-67fae54f7992.png)

**Comment by StevenMMortimer** [comment]
@shambhu112 Just following up if you were able to investigate the issue and whether you were able to configure Okta or setup a OAuth Client within your Salesforce instance.
