### ISSUE TITLE
Error created for Bulk query with zero records in response

### ISSUE THREAD

**Issue by rgustavs** [StevenMMortimer/salesforcer#21]
Hi 
I am getting an error when running bulk query with zero response records. See below for trace

> Error: 'Records not found for this query' does not exist in current working directory ('C:/dev/x'). 
> 9. stop("'", path, "' does not exist", if (!is_absolute_path(path)) paste0(" in current working directory ('", getwd(), "')"), ".", call. = FALSE) 
> 8. check_path(path) 
> 7. standardise_path(file) 
> 6. read_delimited(file, tokenizer, col_names = col_names, col_types = col_types, 
>     locale = locale, skip = skip, skip_empty_rows = skip_empty_rows, 
>     comment = comment, n_max = n_max, guess_max = guess_max, 
>     progress = progress) 
> 5. read_csv(response_text) 
> 4. sf_query_result_bulk(job_id = batch_query_info$jobId, batch_id = batch_query_info$id, 
>     result_id = batch_query_details$result, api_type = "Bulk 1.0", 
>     verbose = verbose) 
> 3. sf_query_bulk() at sf_dump.R#179
> 2. extract_attachement_from_service(record_limit, db) at sf_dump.R#66
> 1. main() 

Would it be possible to get a nicer output from the package?

**Comment by rgustavs** [comment]
Need to doublecheck on my side. Closing :)

**Comment by rgustavs** [comment]
The error is persists.

This may be a feature request "NULL response from sf_query_bulk when there are zero records found by the query"

> sf_query("Select Id from account where Id = 'a11200000000000000'")
NULL
> sf_query_bulk("Select Id from account where Id = 'a11200000000000000'", "Account")
Error: 'Records not found for this query' does not exist in current working directory ('C:/dev/codecommit/bdl-richard-private').
>

**Comment by StevenMMortimer** [comment]
@rgustavs From what I can gather from Salesforce, unofficially, it seems that bulk queries that return zero records in the result are supposed to return a CSV with one line stating "Records not found for this query". I have introduced a snippet of code inside one of the bulk query results getting functions to check for this key phrase and return a zero-row tibble which is how `sf_query()` currently behaves (not yet on CRAN) when specifying `api_type = "REST"` or `api_type = "SOAP"` and running a SOQL that returns no results.

Below is a link to the fix. It worked for me, so hopefully, this is good enough. Otherwise, we can start checking the metadata on the job instead.

https://github.com/StevenMMortimer/salesforcer/blob/f4846a5b693d009275c5f036aef3f61e1c6d6465/R/bulk-query.R#L106
