### ISSUE TITLE
sf_create_attachment results in Error in FUN(X[[i]], ...) : invalid 'file' argument

### ISSUE THREAD

**Issue by TonyWhiteSMS** [StevenMMortimer/salesforcer#42]
Found that the function sf_create_attachment gives the error
Error in FUN(X[[i]], ...) : invalid 'file' argument
When checking the files exist: 
`files_exist <- sapply(head(dat[,column], n_check), file.exists)`

IF you use a data.frame, changing it to build the object with tibble resolves the issue.
```
    attachment_details <- tibble(
        ParentId = caseRecords$id,
        Body = paste(getwd(), csvdata$File, sep="/"),
        Name = sub(".*/(.*)","\\1", csvdata$File)
    )
    print(attachment_details)
    result <- sf_create_attachment(attachment_details, api_type = "REST", verbose = FALSE)
```

Not sure if a bug to be fixed or at least documented warning

**Comment by StevenMMortimer** [comment]
@TonyWhiteSMS The issue is that if you create values using `data.frame()` it will set the data type of any string columns to a  `factor`. Factors create all sorts of problems in R. It is better to include `options(stringsAsFactors=FALSE)` at the top of your scripts to avoid that issue. Tibbles, by default, do not take strings and cast them as factors which is why the function is working with tibbles.

I will create a line of code in `sf_create_attachments()` function that will fail and tell users to convert factor columns to strings so that the source data can be fixed and then passed again to the function.
