### ISSUE TITLE
R 4.0

### ISSUE THREAD

**Issue by pcorvalan** [StevenMMortimer/salesforcer#53]
Hi Steven, 

I would like to ask if you test Salesforcer on R 4.0 environment. 
Does Salesforcer have any dplyr package dependency that may be affected if we upgrade to dplyr 1.0?

Saleforcer is a great package! 

Thanks!

**Comment by StevenMMortimer** [comment]
@pcorvalan Great question. I haven't tested on R 4.0. The current tests were on minor versions **R 3.5** and **dplyr 0.8**. 

I wouldn't expect much to change on **R 4.0**. Most of the references to stringsAsFactors already involved setting it to `FALSE`. 

I'm not so sure about **dplyr 1.0**. My advice is taking a look at the changes in the recent release to spot any potential issues, then upgrade in a dev environment see how it goes. If not, then revert and let me know any issues. Happy to help work through it to make sure it works for everyone.

**Comment by arp3ggio** [comment]
Fwiw, I just upgraded today to `R` 4.0 today on Ubuntu 20.04. I had a few battles to fight getting various `tidyverse` packages re-installed, but `salesforcer` was not a problem. I did receive the following message on my first run:    
`Error: package ‘salesforcer’ was installed before R 4.0.0: please re-install it`

From terminal, I then ran:  
`sudo su - -c "R -e \"devtools::install_github('StevenMMortimer/salesforcer', force = TRUE)\""`

The `force = TRUE` was required because (I believe) `devtools::install_github()` was detecting no changes since prior install. Prior to the above, I also had to re-install `base64enc` and `data.table` per `ERROR` messages on my initial attempts to reinstall `salesforcer`. I likely re-installed the other dependencies listed here as part of reinstalling other packages:  
https://cran.r-project.org/web/packages/salesforcer/index.html

Overall, I could have been a bit more organized before doing the upgrade to `R` 4.0, but I did full disk clone last night, so I was feeling reckless.  

In minimal initial testing (numerous `sf_query` but nothing else), I'm not seeing any issues.

**Comment by StevenMMortimer** [comment]
Thanks, @arp3ggio! Appreciate the detail here. Very helpful. Keep me posted if anything pops up.

**Comment by pcorvalan** [comment]
Thanks @arp3ggio !!

**Comment by arp3ggio** [comment]
Additional background, I'm also using `dplyr` version `0.8.99.9003` from github. Since my prior post, I've not seen any problems with numerous `sf_create`.

**Comment by danwwilson** [comment]
I was just trying to use `sf_query()` with the bulk API and got the following error

```
Error: Unknown TZ UTC
In addition: Warning message:
In OlsonNames() : no Olson database found
```

I did some tracing and the error occurs at line 52 of `sf_create_job_bulk_v1()` with the statement
``` r
job_info <- response_parsed %>% xml_ns_strip() %>% xml_find_all("//jobInfo") %>% 
    map_df(xml_nodeset_to_df) %>% type_convert(col_types = cols())
```

I had the issue myself the other day with another function of mine as the result of using a posixct in an interval function, but given this issue is the result of the `type_convert` it could be due to some sort of missing timezone information.

**Comment by StevenMMortimer** [comment]
@danwwilson After some googling, I think it could be more of a system configuration issue where **readr** cannot find the Olson database on the system needed to parse datetimes. Could you check out the two similar issues I've linked below and let me know if these explain/solve the issue? Thanks.

- *Why does readr::read_csv need timezone data and Olson database?* - https://github.com/tidyverse/readr/issues/952
- *R missing timezone data and Olson database* - https://github.com/jupyter/docker-stacks/issues/502

**Comment by danwwilson** [comment]
@StevenMMortimer adding the tzdata to the docker build solved the problem. Thanks a Buch for your help.

**Comment by StevenMMortimer** [comment]
@pcorvalan @arp3ggio @danwwilson I've now tested and built the package on Windows, Ubuntu, and Mac OS X across multiple version of R, namely 3.6.3, 4.0.0, and 4.0.1 (more specifics on the tested configurations are available in [cran-comments.md](https://github.com/StevenMMortimer/salesforcer/blob/master/cran-comments.md)). I didn't encounter any problems with unit tests or installs. As @arp3ggio keenly pointed out, you may have to work through some issues installing the dependencies, but no trouble after that.

Please let me know if there are still problems and we can work through them. If there are no lingering issues or I don't hear back in a couple weeks, then I'll close this issue. 

**Thanks again for your assistance and your patience!** 👍

**Comment by pcorvalan** [comment]
Thanks Steven! We upgraded R base in a test machine without any problem.
Best regards.
