### ISSUE TITLE
Can't Add Records to just created Custom Object

### ISSUE THREAD

**Issue by Btibert3** [StevenMMortimer/salesforcer#8]
I had an idea for a blog post, but I ran into an error that I didn't see coming and admittedly am not sure what I am doing, though its probably on my end.  

In short, I am creating a custom object on the fly, adding a couple of fields, and then I want to throw data into those fields.  Everything works as expected until I try to insert the test record, with the error telling me that the two fields do not exist, though they are clearly visible on the object within SFDC.

That said, if I point/click the new fields, I can add the same test record.

```
###################### define the core info for the custom object
base_obj_name <- "ExampleObject"
custom_object <- list()
custom_object$fullName <- paste0(base_obj_name, "__c")
custom_object$label <- paste0(gsub("_", " ", base_obj_name))
custom_object$pluralLabel <- paste0(base_obj_name, "s")

## define the core name field as an autonumber
custom_object$nameField <- list(displayFormat = 'CM-{0000}', 
                                label = paste0(base_obj_name, ' Number'), 
                                type = 'AutoNumber')

## additional settings for the custom object
custom_object$deploymentStatus <- 'Deployed'
custom_object$sharingModel <- 'ReadWrite'
custom_object$enableActivities <- 'true'
custom_object$description <- paste0(base_obj_name, " created by the Metadata API")
custom_object$FIELD_INTEGRITY_EXCEPTION <- 'Deployed'

## deploy the object into our org
custom_object_result <- sf_create_metadata(metadata_type = 'CustomObject',
                                           metadata = custom_object)


###################### create two fields

## custom field for database id -- assumes the data are being imported
cf1 <- tibble(fullName=c(paste0(base_obj_name, '__c.MyDbId__c')),
                        label=c('External Database Id'), 
                        type=c('Number'),
                        precision = 10,  ## how large is the number on both side of decimal
                        scale = 0,  ## how many to the right of the decimal
                        required="false",
                        unique="true",
                        externalId="true")
cf1_result <- sf_create_metadata(metadata_type = 'CustomField', 
                                 metadata = cf1)


## a long text field
cf2 <- tibble(fullName=c(paste0(base_obj_name, '__c.SomeText__c')),
                        label=c('Chat Message'), 
                        type=c('LongTextArea'),
                        length = 1000,
                        visibleLines = 4)
cf2_result <- sf_create_metadata(metadata_type = 'CustomField', 
                                 metadata = cf2)

## check the successes
cf1_result; cf2_result;

## put 1 record in
my_r = tibble(MyDbId__c = 1,
              SomeText__c = "Hello World")
add1 = sf_create(my_r, object_name = custom_object$fullName)
```

`add1` shows me this error:

```
> add1$errors.message
[1] "ExampleObject__c: bad field names on insert/update call: SomeText__c, MyDbId__c"
```

But after pointing/clicking the fields, I can add the data, so its something about programmatically creating the fields that is tripping me up.

```
my_r2 = tibble(MyDbID2__c = 1,
              Some_Text2__c = "Hello World")
add2 = sf_create(my_r2, object_name = custom_object$fullName)

## status of attempt to put data into point/click fields
> add2
# A tibble: 1 x 2
  id                 success
  <chr>              <chr>  
1 a02f200000f8I9sAAE true   
```

<img width="1407" alt="example-object-error" src="https://user-images.githubusercontent.com/203343/42411766-dc5db390-81cf-11e8-93b8-18384bd9fbac.png">

**Comment by Btibert3** [comment]
As I thought about this today, it seems like it might be related to the field-level security for the newly created field.  Is there a way to set that via the currently included functions?

Here is a related-ish question:

https://salesforce.stackexchange.com/questions/34521/set-field-level-security-for-profile-using-meta-data-api/58243#58243

**Comment by StevenMMortimer** [comment]
It appears that when deploying custom fields they are not editable by default. 

![image](https://user-images.githubusercontent.com/5299737/42427284-a053d622-82fb-11e8-8a3b-283a1a75b9c8.png)

https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_profile.htm#profilefieldlevelsecurity_title

I didn't know this, but it seems like the field would need to be updated in a second call after creating it.

**Comment by StevenMMortimer** [comment]
@Btibert3 You would need to update the ProfileFieldLevelSecurity metadata for your profile (and probably other users' profiles as well) before you can insert records. First, I would recommend pulling down a list of all the different profiles in your organization. You can get that list of profiles using `sf_list_metadata()` like this: 

```
my_queries <- list(list(type='Profile'))
profiles_list <- sf_list_metadata(queries=my_queries)
```

In my org, one of the profiles is "Admin". Assuming you are an Admin user, then you will need to update the ProfileFieldLevelSecurity for the "Admin" profile. You can do that like this: 

```
prof_update <- sf_update_metadata(metadata_type='Profile', 
                                  metadata=list(fullName='Admin', 
                                                fieldPermissions=list(field=paste0(base_obj_name, '__c.SomeText__c'),
                                                                      editable='true'), 
                                                fieldPermissions=list(field=paste0(base_obj_name, '__c.MyDbId__c'),
                                                                      editable='true')))
> prof_update
# A tibble: 1 x 2
  fullName success
  <chr>    <chr>  
1 Admin    true   
```

Once you've updated the relevant profiles, then you can insert records just like you were doing above: 

```
> my_r = tibble(MyDbId__c = 1,
+               SomeText__c = "Hello World")
> add1 = sf_create(my_r, object_name = custom_object$fullName)
> add1
# A tibble: 1 x 2
  id                 success
  <chr>              <chr>  
1 a0C6A000004Cl3TUAS true  
```

**Comment by Btibert3** [comment]
A+ sir.

Where/how can I start to wrap my head around the syntax.  Your functions clearly are extensible, so what would you recommend in terms of how to work through some of these myself?

Absolutely fantastic.

**Comment by StevenMMortimer** [comment]
@Btibert3 I'll be honest, it's not easy to read through the documentation and try a bunch of things until you finally figure out what you need to pass over to the API. The first place I'd recommend looking when you want to work with the Metadata API is the list of Metadata types, which is available here: https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_types_list.htm

The Metadata API allows you to create, read, update, and delete any of these object types. With your question on changing a profile setting, I just looked at the documentation for the [`Profile object`](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_profile.htm). 

When looking at the object's page you'll see the text:
>`The profile definition contains the following fields:`... 

Right there it lists everything that makes up a `Profile` object. The first field of a `Profile` object is called `applicationVisibilities` and its field type is `ProfileApplicationVisibility[]`, which means that if you are updating a profile's application visibilities, then you will need to supply a list of objects that are of the type `ProfileApplicationVisibility`. If you [click](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_profile.htm#profileapplicationvisibility_title) on that field type you'll see that `ProfileApplicationVisibility` is an object that has 3 fields, `application`, `default`, and `visible` which are either strings or boolean values. So in order to create a `ProfileApplicationVisibility` object, you need a list with those field names specified with string or boolean values depending on what each field requires. Anytime an object contains fields that are other complex objects and not primitive types, then the object starts to become nested and requires a list structure in R to emulate that. If you're just inserting data onto an Account object all the data is just strings, booleans, etc. so it's easy for the package to assume that each row in your data.frame is a new record, but with objects it becomes much harder to guess on what the user input means and thus, you must use lists to really emulate the nested structure of complex object types. 

You are right that the functions in the **salesforcer** package are extensible. They should support any Metadata API operation that a person could do, but you need the inputs to be formatted correctly. One additional tip I would give is to turn on `verbose=TRUE` so that you can see the generated XML and the URL endpoint it's being sent to. You'll find examples on StackOverflow and other sites that can point you towards what the XML needs to look like in order for things to work. 

Finally, I'm impressed by how much you're doing with the package and I love the questions you're asking because I haven't even thought of all the ways to utilize the APIs. Every question is another chance to flesh things out and add to the vignettes or documentation. I'll probably write up a vignette on creating custom objects, adding custom fields, turning on the right profile field level security, and inserting records all because of the questions you've brought up and that will greatly help others. Just let me know if there's anything else I can help with.

**Comment by Btibert3** [comment]
This is fantastic, thanks again for all of the help

**Comment by Btibert3** [comment]
Coming back to this, and I am sure that this is on my end, I included `verbose=TRUE` as you can see in the screenshot, and while I got the endpoint, I didn't see the XML request.  The record was created (with some values and 1 field custom to my org), but I was hoping that I might be able to use my `R` code as a POC and the generated XML to help guide my dev team on how to scale this for our internal need.
<img width="715" alt="screen shot 2018-07-19 at 11 41 00 pm" src="https://user-images.githubusercontent.com/203343/42982009-39f014b2-8bad-11e8-81ec-fee3a10d066f.png">

**Comment by StevenMMortimer** [comment]
@Btibert3 I'll open up a separate issue to add XML or JSON printing for all requests. I think currently, only the Metadata and Bulk 1.0 API requests print their XML when `verbose=TRUE`. The SOAP, REST, and Bulk 2.0 APIs don't have that level of printing probably because I wasn't debugging them as much when I wrote those modules.
