### ISSUE TITLE
Data Loader Functionality

### ISSUE THREAD

**Issue by jessecambon** [StevenMMortimer/salesforcer#96]
I'm new to the Salesforce API, but I am curious how feasible it might be to use this package (or an API query in general) as a replacement for [Salesforce Data Loader](https://developer.salesforce.com/docs/atlas.en-us.dataLoader.meta/dataLoader/data_loader.htm) (this is in Salesforce Lightning). 

I was attempting to use the `sf_create_attachment()` function to replace a data loader process, but I found that the files I uploaded came in as "Attachments" or "Documents"  which I could not get to attach to records. In the data loader process the files were attached to records directly as ["Files"](https://admin.salesforce.com/blog/2017/pro-tip-simplify-file-management-salesforce-files-lightning-experience#:~:text=In%20Lightning%20Experience%2C%20Salesforce%20Files,they%20are%20in%20the%20app) (which is what I'm trying to do).

**Comment by StevenMMortimer** [comment]
If you want to upload a file to Salesforce and associate it to a record, then you just need to provide a value in the `ParentId` field when you upload the content. Below is a link to the Bulk API documentation which helps to highlight what other fields you can specify in the upload process, besides the content itself.

https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/binary_create_request_file.htm.

Let me know if that helps answer your question. Pretty much anything you can do with Data Loader can also be done with this package. Like Data Loader, you will need to understand the quirks of Salesforce's data models and the tool's interface to it (`salesforcer` in this case, instead of Data Loader).

**Comment by jessecambon** [comment]
Thanks, that's good to know. So in theory, I should be able to accomplish what file loader is doing with code similar to this?

```r
file_path1 <- here::here("doc1.pdf")
file_path2 <- here::here("doc2.pdf")
parent_record_id <- "0036A000002C6MmQAK"
attachment_details <- tibble(Body = c(file_path1, file_path2), 
                             ParentId = rep(parent_record_id, 2))
result <- sf_create_attachment(attachment_details)
```

The issue I ran into with this approach was that the attachment would upload to the `Attachments` table, but it would not attach to the record.

**Comment by StevenMMortimer** [comment]
@jessecambon Yep, that should work as you've written. Note that you can also use the bulk API if you're planning to do a big migration or uploading lots of content at once. It basically reduces the need to do things in many small batches since the SOAP and REST APIs have size limits on the requests.

**Comment by StevenMMortimer** [comment]
@jessecambon Heads up that I'll close this issue in a couple days if you don't have more to add right now. If you encounter a bug or have a feature request, then feel free to re-open here or create a new issue.

**Comment by bcaessens** [comment]
Hi Steven and Jesse,

Sorry to re-open this issue, but I still can't figure out how to properly have Documents uploaded using the salesforcer package. The code example for attachments works, however, attachments currently won't show up in salesforce. So we want pdf's to show up under AttachedContentDocument. 
I have found the example using the Document content type, however, it requires a FolderId. My guess is, this is the FolderId related to the record of interest (where we want to link those files) or is it something completely different? 

Totally lost here. Any help would be great. So basically, I want to add a pdf to Documents (visible in salesforce) to an Order for which I have the OrderId. 

Thanks in advance,
Bernie.

**Comment by StevenMMortimer** [comment]
@bcaessens Thanks for posting the solution back on here for others to follow!
